[package]
name = "zero"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "example_scene"
path = "bin/example_scene.rs"

[[bin]]
name = "example_scene_headless"
path = "bin/example_scene_headless.rs"
required-features = ["headless"]

[features]
default = []
headless = []

[dependencies]
winit = "0.26"
wgpu = "0.12"
bytemuck = { version = "1.4", features = [ "derive" ] }
cgmath = "0.18"
pollster = "0.2"
image = "0.23"
tobj = { version = "3.0", features = [ "log" ] }
hexasphere = "7.0.0"
anyhow = "1.0"
env_logger = "0.9"
log = "0.4"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
