[package]
name = "zero"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[example]]
name = "scene"
path = "examples/scene.rs"

[[example]]
name = "scene_headless"
path = "examples/scene_headless.rs"
required-features = ["headless"]

[features]
default = ["x11"]
headless = []

wayland = ["winit/wayland"]
x11 = ["winit/x11"]

[dependencies]
winit = { version = "0.26.0", default-features = false }
wgpu = { version = "0.13", features = ["spirv"] }
bytemuck = { version = "1.4", features = [ "derive" ] }
tobj = { version = "3.0", features = [ "log" ] }
hexasphere = "7.0.0"
env_logger = "0.9"
pollster = "0.2"
cgmath = "0.18"
anyhow = "1.0"
image = "0.23"
log = "0.4"

[build-dependencies]
fs_extra = "1.2"
anyhow = "1.0"
glob = "0.3"
